# Website specifications
title: "IEEE SBAC-PAD 2023" # Website's name
description: 35th IEEE International Symposium on Computer Architecture and High Performance Computing
url: "https://cradrs.github.io/sbacpad2023" # Website's base hostname and protocol (e.g.: http://example.com)
baseurl: "/sbacpad2023" # Website's subpath (e.g.: /blog)
final_url: https://cradrs.github.io/sbacpad2023

# Website collections
collections_dir: collections
collections:
    news:
    keynote_speakers:
        sort_by: order

# Website SASS settings
sass:
    sass_dir: _sass
    style: compressed

# Jekyll plugins
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
